from itertools import combinations
samples = [
    "clustal_aib", "muscle_aib", "kalig_aib",
    "clustal_aib_permuted", "muscle_aib_permuted", "kalig_aib_permuted",
    ]
rule all:
    input:
        expand("trees/{sample}_{method}.newick", sample = samples, method = ['quicktree', 'rapidnj'])

rule quicktree:
    input: 
        "alignments/{sample}_truncated.stockholm"
    output:  
        "trees/{sample}_quicktree.newick"
    shell:
        "quicktree {input} > {output}"


rule rapidnj:
    input: 
        "alignments/{sample}_truncated.fasta"
    output:  
        "trees/{sample}_rapidnj.newick"
    shell:
        'rapidnj -i fa {input} > {output}'

rule truncate_fasta:
    input:
        'alignments/{sample}.fasta'
    output:
        'alignments/{sample}_truncated.fasta'
    shell:
        "cut -d '|' -f-2 {input} > {output}"

rule fasta2stockholm:
    input:
        'alignments/{sample}_truncated.fasta'
    output:
        "alignments/{sample}_truncated.stockholm"
    shell:
        "python fasta2stock.py {input} > {output}"

rule prepare_input:
    input: 
        expand(
            'input/{sample}_truncated.fasta',
            sample = ['patbase_aibtas_permuted', 'patbase_aibtas'] 
            )